version: 2

gen_cache_key: &gen_cache_key
  run:
    name: Generate cache key
    command: |
      sudo chmod +x ./checksum.sh
      ./checksum.sh /tmp/checksum.txt

restore_cache: &restore_cache
  restore_cache:
    key: gradle-{{ checksum "/tmp/checksum.txt" }}

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
    key: gradle-{{ checksum "/tmp/checksum.txt" }}

download_dependencies: &download_dependencies
  run:
    name: Download dependencies
    command: |
      sudo chmod +x ./gradlew
      ./gradlew androidDependencies

setup_environment_variables: &setup_environment_variables
  run:
    name: Setup environment variables
    command: |
      echo "export ANDROID_NDK_HOME= >> $BASH_ENV

jobs:
  build:
    working_directory: ~/tellMe-android-app
    docker:
      - image: circleci/android:api-29
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"

    steps:
      - <<: *setup_environment_variables
      - checkout
      - <<: *gen_cache_key
      - <<: *restore_cache
      - <<: *download_dependencies
      - run:
          name: Run lint
          command: ./gradlew app:lintDebug
      - run:
          name: Check code style
          command: ./gradlew spotlessCheck
      - run:
          name: Assemble debug
          command: ./gradlew assembleDebug --scan --stacktrace
      - <<: *save_cache
      - run:
          name: Run tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results